node 
{
    deleteDir()
    String[] arr = [ "https://github.com/PratapSingh13/Java.git", "https://github.com/PratapSingh13/Shared-Library.git", "https://github.com/PratapSingh13/Java.git" ] 
    stage('Cloning Repository')
    {
        for (repo in arr) 
        {
            split_url = repo.split('/')
            repo_name =  split_url[split_url.length-1]
            split_repo = repo_name.split('.git')
            project = split_repo[0]
            sh "echo $project"
            sh "rm -rf *"
            sh "mkdir AWS"
            dir("AWS") 
            {
                git credentialsId: 'GitHub', url: "${repo}"
                
                stage ('Installing Git Secrets')
                {
                    sh label: '', script: 'git secrets --install'
                }
            
                stage ('Registering AWS')
                {
                    sh label: '', script: 'git secrets --register-aws'
                }
            
                stage ('Scanning Repository')
                {
                    try
                    {
                        sh label: '', script: '{ git secrets --scan; } 2> secretkeys.txt | true'
                        sh "cp secretkeys.txt ${project}.txt"
                        sh "cat ${project}.txt"
                        googlechatnotification message: 'MSG for Testing', 
                        notifySuccess: false, 
                        sameThreadNotification: false, 
                        suppressInfoLoggers: false, 
                        url: 'https://chat.googleapis.com/v1/spaces/AAAAuvH0DTI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=6bxkYEGZWPNi1G449fc7FCvyX7PP5v6Xx1rLo3uWLTE%3D'
                    }
                    catch (Exception e)
                    {
                        emailext attachmentsPattern: """${project}.txt""", 
                        body: 'Hi Team, \n\n\nPlease find AWS report generated by jenkins', 
                        recipientProviders: [buildUser()], subject: 'AWS Credentials file', 
                        to: 'yogendrapratapsingh70@gmail.com'
                    }
                }
            }
        }
    }
}
